### ISSUE TITLE
How to pass native Java callbacks like in Python's Jsonnet binding

### ISSUE THREAD

**Issue by bankotsu** [databricks/sjsonnet#102]
When sjsonnet is used from Java or as a standalone executable assembly, is there a way to inject native Java functionality (such as `Pattern.quote()`) to the jsonnet evaluator? i want to be able to execute simple Java code from within the jsonnet/sjsonnet code as can be performed with Python's jsonnet bindings using the `evaluate_file` function and passing the `native_callbacks` argument, and being able to invoke these callbacks using `std.native(...)` from within the jsonnet file.

![image](https://user-images.githubusercontent.com/13404522/99018006-cb6e7000-2561-11eb-8295-aba1197c103f.png)

**Comment by lihaoyi-databricks** [comment]
Since https://github.com/databricks/sjsonnet/pull/166 merged, we should be able to pass in callbacks through the Scala API whether you are using `sjsonnet.SjsonnetMain.main0` or `sjsonnet.Interpreter`. This problem then reduces to needing to provide an idiomatic Java API, which we can track as part of https://github.com/databricks/sjsonnet/issues/157
