### ISSUE TITLE
Is it secure to run user jsonnet snippets?

### ISSUE THREAD

**Issue by buremba** [databricks/sjsonnet#61]
We're planning to use the library in our web app where the developers can write Jsonnet snippets and run it on our servers. 

1. We have a custom importer so ideally, the users won't be able to have access to the underlying operating system's filesystem.
2. There is already a native limitation for the recursive programs (JVM stack size limit) which is great for us in case the user tries to exhaust the CPU by compiling deeply recursive Jsonnet snippets.
3. If I'm not mistaken, sjsonnet does not provide any way for the Jsonnet programs to execute JVM methods, the `std.*` functions run in a sandbox.
4. If there is any way to limit the memory consumption while parsing the Jsonnet programs, it would be great. I'm not sure if it's possible to exhaust the memory by compiling recursive programs that generate heavy map/list-objects but either way, the JVM stack size limit would probably help us here as well.

Can someone give some info about the security aspect of the project?

**Comment by lihaoyi-databricks** [comment]
To answer this a few years late, Sjsonnet allows you to prevent the user from performing unsafe actions, because they are limited to what they can `import` and the builtin `std.*` functions to do things.

Sjsonnet does not provide any sort of resource control. Running on a shared JVM, there is nothing stopping a Sjsonnet interpreter from hogging the CPU, or allocating enough memory to cause an OOM. Jsonnet is in general a turing complete language, so preventing these failure modes statically is impossible, and the JVM does not provide the necessary tools to mitigate them at runtime.

If you need to run truly-untrusted Jsonnet code, you are best served by running Sjsonnet in a child process or container. That way you can limit the memory and CPU allocated to it.
