### ISSUE TITLE
Various incompatibilities with go-jsonnet

### ISSUE THREAD

**Issue by Qinusty** [databricks/sjsonnet#73]
I would like to bring this project towards further compatibility with the go and c++ implementations. I hope this ticket can act as a tracking ticket for various issues between the implementations.

As a start, I would like to integrate the [testdata](https://github.com/google/go-jsonnet/tree/master/testdata) from go-jsonnet into the testing pipelines in this project. The tests provide a huge selection of test sources and golden files to match against.

**Comment by lihaoyi-databricks** [comment]
I think I've hammered out most of the issues, except for a few like `parseYaml`/`manifestToml`/`deepJoin`. These should be addable by end-users now, since we now allow the `std` to be injected or configured externally, so hopefully someone adds them to their own project to scratch their own itch and sends a PR back upstream.

I'm going to close this ticket for now, because the other issues already have their own tickets, so not much value in keeping this one around.
