### ISSUE TITLE
Lazy evaluation 

### ISSUE THREAD

**Issue by derrickburns** [databricks/sjsonnet#93]
I have code that run fine with the go jsonnet interpreter but causes infinite recursion with sjsonnet.  That code uses lazy evaluation. Is this a known area where a) the language is ill defined b) there are known bugs in one or both of the compilers?

**Comment by sbarzowski** [comment]
Hi @derrickburns, go-jsonnet dev here. 

It would probably be much easier to answer this question with an example, without it, we can only speculate. Is your problem related to object assertions?

There exists one known issue, which might be related – https://github.com/google/jsonnet/issues/451. Basically, the spec mandates infinite loop in some cases. but both cpp-jsonnet and go-jsonnet (not sure about sjsonnet) make it work. It is very hard to fix, because technically the current behavior violates referential transparency, but some users depend on it. It's a bit of a boundary case, can be worked around and only concerns additional validations (it never causes a wrong output, just looping vs not looping in some cases), so we didn't rush with fixing it.

**Comment by derrickburns** [comment]
@sbarzowski Thanks for the response.  I did not post an example because a) it was obtuse and b) it didn't really deserve much attention.  I think the code falls in the boundary case that you describe.  I rewrote it to remove the need for lazy evaluation.  Thx!
